### ISSUE TITLE
Questions about performing 2D simulations etc

### ISSUE THREAD

**Issue by Bradleydi** [toastedcrumpets/DynamO#50]
Hi Marcus,

I wanna perform 2D simulations with DynamO but found no such function available. I tried letting z and v_z=0 but found problems happened about temperature (3D thermostat may not hold for 2D). Could you extend it to 2D case? Besides, how to dump particles' info (xyz v_xyz) every N steps or events which used for data analysis in equilbrium state but not trajectories. 

Another request is that how about extenting parallel cudes to general cubes because general cubes have more interesting phenomena to explore.

Thank you so much!
Best

**Comment by toastedcrumpets** [comment]
You can already do 2D. For the thermostat there is an option which I've just documented called "dimensions", which sets how many dimensions to thermostat. See this http://dynamomd.org/index.php/reference#typeandersen
for more info.

To dump data every N events, use the --snapshot-events X option of dynarun. This will save a config file every X events.

Finally, non-parallel cubes are much more difficult to implement than parallel cubes which is why they are not implemented. However, I am working on a general framework for this so you will see it in the future.
Kind regards,
Marcus

**Comment by Bradleydi** [comment]
Thank you for your reply, But I didn't find dimensions in Andersen thermostat.

How should I perform 2D? The current way I use is to write the configuration file by myself and set all particles in the x-y plane(all z=0). and <SimulationSize x="10" y="10" z="10"/> (not z=0). There will be problems if vz is not exact zero and the densities for 2D and 3D systems are different. Any other good ways to do 2D?

Thank you so much!
Best

**Comment by toastedcrumpets** [comment]
Here is an example 2D thermostatted configuration:
https://gist.github.com/c12b858ba0846a7c0fdb.git
You'll notice that all particles are at z=0 with a z-velocity of zero. The thermostat also has the Dimensions="2" attribute set.

You may not see the "dimensions" tag in the online documentation until you refresh your browser, as I only just added it.
Hope this helps!
Marcus

**Comment by Bradleydi** [comment]
Is there any command available for 2D simulation or any example?
Maybe one example is better than my days' exploration and questions.

I have seen your update. Thank you so much!
Best

**Comment by toastedcrumpets** [comment]
You can make 2D configurations using this "style" of dynamod command:
./dynamod  -m 0 --i1=2 -C 7 -x 1 --rectangular-box
But this does not correctly set the dimensions tag. Please see this configuration file for an example:
https://gist.github.com/toastedcrumpets/c12b858ba0846a7c0fdb
(the link was wrong before, I've just corrected it)
