### ISSUE TITLE
Compiling on the Mac with gcc 4.9: no-as-needed issue

### ISSUE THREAD

**Issue by FTurci** [toastedcrumpets/DynamO#51]
Hello,
I am compiling DynamO on Mac OS X 10.9 using Homerbrew gcc 4.9. 

There are two surprising issue during the compilation step:
1) despite using gcc 4.9, cmake highlights that my compiler does not support C++0x/11 fully

    CMake Warning at CMakeLists.txt:91 (message):
        Although the compiler advertises support for C++0x/11, this support is
        broken (e.g., gcc-4.8.2).  You can only compile a limited version of DynamO (simple potentials only).''

2) when proceed to make, i get the following error at the last linking step
    
    [ 98%] Building CXX object   
    CMakeFiles/magnet_threadpool_test_exe.dir/src/magnet/tests/threadpool_test.cpp.o
    Linking CXX executable magnet_threadpool_test_exe
    ld: unknown option: --no-as-needed

Any idea on how to have a clean installation?

**Comment by toastedcrumpets** [comment]
Hi,
I'm currently traveling so I can't look into this for a few days, but the
first issue might be due to a cached configure check? Could you try
deleting the build dir and trying again?

The second issue can be solved (temporarily) by deleting this line
https://github.com/toastedcrumpets/DynamO/blob/master/CMakeLists.txt#L227
However, the code should have still completed building even with that
error. Do you have a dynarun and dynamod executable in the build directory?
Kind regards,
Marcus

**Comment by toastedcrumpets** [comment]
Hi, did this get resolved in the end?
Marcus

**Comment by FTurci** [comment]
Hi, sorry for the late reply.

Modifying the line that you indicated actually solved the second issue. The first, yet, seems to still be there. 

However, the executable is actually working at least for the simple potentials I am testing it with, so, thank you!

**Comment by toastedcrumpets** [comment]
OK, I'll close this for now, as the compiler check is doing what it should (not enabling adv. potential support yet). This support is still limited to the really advanced potentials so its not likely you'll need this yet.
Marcus
