### ISSUE TITLE
How to save time when 'snapshot mode on'

### ISSUE THREAD

**Issue by huijun-zhang** [toastedcrumpets/DynamO#52]
Dear all,
I want to calculate some other correlation functions that the DynamO does not build-in, so I need to periodic snapshot (particles configurations). While I set "--snapshot 1" mode on, I found the periodic output file also dumped out. These output files including collected data are awfully large.
Does the dumping of the output_data can be controlled as I need?

Thank you very mush!
Huijun

**Comment by toastedcrumpets** [comment]
Periodic output is always given with the snapshots, the amount of data in these dumps is not very large by default when compared to the configuration. I haven't currently got a way of disabling this output either.

Please note, you can reduce the amount of output by using Equilibrium mode in dynarun (''-e"). This disables all output plugins and so produces little or no output.

**Comment by huijun-zhang** [comment]
Hi Marcus,
Thank you very much!
I want to disable the Snapshot.out.*.xml.bz2
I found that the huge output data is related to some "-L" plugins on, such as "-L MSDCorrelator". These informations are all included in "Snapshot.out.*.xml.bz2". Besides, "-E" mode can not disable Snapshot.out files which will take huge space and time. Maybe I can perform  a single run to get long-time MSDCorrelator, and again run another one to gather configurations.

**Comment by toastedcrumpets** [comment]
Hi,
I see your problem. I think the real issue is that certain output plugins output a lot of data. MSDCorrelator is one of them. If you are currently collecting snapshots it is actually very easy to calculate the MSDCorrelator from them directly as all snapshots are saved in "unfolded" coordinates.

I don't really want to change the current behaviour of DynamO as a lot of people rely on the dual snapshot and output mode. Can you tell me which plugins you're using that are causing a lot of output? Is it just MSDCorrelator?
Kind regards,
Marcus
